### ISSUE TITLE
Making model for each post when clicked (UI only )

### ISSUE THREAD

**Issue by loneWarrior581** [dkp1903/devagram#43]
## Making a post model for each post when clicked having the _post image_ on left and _comments_ on right.

<img src="https://icdn2.digitaltrends.com/image/digitaltrends/saving-instagram-posts-416x416.jpg"/>

**Comment by MananDesai54** [comment]
I'm On it

**Comment by MananDesai54** [comment]
@loneWarrior581 close this Issue, it's done
