### ISSUE TITLE
Making ShowStory component for The story which is clicked.

### ISSUE THREAD

**Issue by MananDesai54** [dkp1903/devagram#44]
![image](https://user-images.githubusercontent.com/52067783/98267060-f892af80-1fb0-11eb-8109-0f6aeafee3ab.png)
Make UI only, not need to implement that GOTO previous or next buttons now.

**Comment by loneWarrior581** [comment]
We can use the [react-insta-story](https://www.npmjs.com/package/react-insta-stories) package for this purpose

**Comment by MananDesai54** [comment]
I am on it

**Comment by MananDesai54** [comment]
Done
